### ISSUE TITLE
Feature Request: Tab Title Override

### ISSUE THREAD

**Issue by acuozzo** [FFDA/ThunderWebTabs#1]
Thank you so much for this! With your extension I'm able to keep all of my "discussions" in one place: e-mail, Usenet, IRC, (and thanks to you...) Reddit, and HackerNews.

Would it be possible to provide a configuration option to override the tab title?

**Comment by FFDA** [comment]
I would think so, but I need to look into that. I will do that when I get a chance.

In the meantime, could you please provide more detail on how you imagine this function? Do you need an extra field in the addon options, or would you prefer a field in the pop-up window next to the site's URL field? Perhaps both?

**Comment by acuozzo** [comment]
I'm thinking just an additional field in the addon options would be sufficient.

I've run across several websites recently which have empty or nonsense title tags. Also, some websites are more-or-less SPAs, but play games with the titling.

**Comment by FFDA** [comment]
So I started reading up on how to implement this feature and found out that someone actually made an add-on (ported from Chrome) for Firefox that does everything you want and more. It actually has more features than what I would have made. It allows changing icons, using regex to match page URLs, and inserting data from the page into the new title.

You can check it out [here](https://addons.mozilla.org/en-US/firefox/addon/tab_modifier/)

I tested it, and it works perfectly. The only issue is that it's not available in the add-on store. So, you have to download it from the Firefox add-on page and install it manually. To download the add-on, just right-click on the "Add to Firefox" button and save the XPI file somewhere.

**Comment by acuozzo** [comment]
Awesome! TY!!!
